---
name: Build multitool docker image (Forgejo)

on:
  pull_request:
  push:
    paths:
      - 'multitool/**'
      - 'multitool/*'
    branches:
      - main
  schedule:
    - cron: "10 2 * * 0"
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.as73.inetsix.net
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: multitool/
          file: multitool/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
          push: true
          tags: git.as73.inetsix.net/docker/multitool:latest
          build-args: |
            SOURCE_REPO_URL=https://git.as73.inetsix.net/docker/docker-network-toolkit

