---
name: Build tacacs-server docker image (Forgejo)

on:
  pull_request:
  push:
    paths:
      - 'tacacs-server/**'
      - 'tacacs-server/*'
    branches:
      - main
  schedule:
    - cron: "10 2 * * 0"
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.as73.inetsix.net
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push Ubuntu image
        uses: docker/build-push-action@v5
        with:
          context: tacacs-server/
          file: tacacs-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            git.as73.inetsix.net/docker/tacacs-plus:latest
            git.as73.inetsix.net/docker/tacacs-plus:ubuntu
          build-args: |
            SOURCE_REPO_URL=https://git.as73.inetsix.net/docker/docker-network-toolkit

      - name: Build and push Alpine image
        uses: docker/build-push-action@v5
        with:
          context: tacacs-server/
          file: tacacs-server/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: git.as73.inetsix.net/docker/tacacs-plus:alpine
          build-args: |
            SOURCE_REPO_URL=https://git.as73.inetsix.net/docker/docker-network-toolkit

