---
name: Build ssh-server docker image

on:
  pull_request:
  push:
    paths:
      - 'ssh-server/**'
      - 'ssh-server/*'
    branches:
      - main
  # schedule:
  #   - cron: "10 2 * * 0"
  workflow_dispatch:

jobs:
  # If on main branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5
        with:
          context: ssh-server/
          file: ssh-server/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_SSH }}:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKER_IMAGE_SSH }}
          readme-filepath: ssh-server/README.md